### ISSUE TITLE
RegexPatterns embedded on input

### ISSUE THREAD

**Issue by leonardofernandescosta** [Rocketseat/unform#101]
**What would you like to be added**:

A new prop that will add some pre-set regex validtion to input.

**Why is this needed**:

Validate input is a major thing in forms. It would be nice to have some pre-set patterns for the developer to choose, without having to code it.

**Additional context**

Something like:  `<Input patternCep></Input>`

patternCep looks like: [0-9]{5}-[\d]{3}

**Comment by jpdemagalhaes** [comment]
Hi @leonardofernandescosta thanks for the suggestion! 

Unform isn't and should not be responsible for validation itself, we use `Yup` for that, meaning that all of our validations should occur through `Yup`. You can check some examples [here](https://github.com/Rocketseat/unform#validation).

Also, on one note, Unform is meant to be a universal library, which makes all validation extremely personal to the user. In each country zip code (our CEP) has a different format, the same goes for phone numbers. Providing this out of the box would be extremely difficult.

One of the reasons why we chose `Yup` as our validation tool is because it is very complete in terms of validation, you can take a look at their github [here](https://github.com/jquense/yup).

To do what you suggested with yup would be as simple as:

```js
const schema = Yup.object().shape({
  zip_code: Yup.string().matches(/[0-9]{5}-[\d]{3}/, 'Please enter a valid zipcode')
});

<Form schema={schema}>
  <Input type="text" name="zip_code" />
</Form>
```

I'll be closing this since we have no intentions right now to add another means of validation inside Unform, but feel free to reopen this in case you think we missed something (or even open a new issue).

Thanks ❤️

**Comment by eltonmarques96** [comment]
Is there some way to integrate the unform with any kind validation?
e.g: In many of cases, is needed to check if zip code is valid using the brazilian post company API, so could we update the unform fields with the data returned from that API?
