### ISSUE TITLE
Usage example/Demo

### ISSUE THREAD

**Issue by zaguiini** [Rocketseat/unform#103]
**What would you like to be added**:

It would be really nice if we could provide a demonstration of the package usage, with the code, preferentially at Code Sandbox. It would be a quick way to show what unform is all about and how it works.

It's really cool to show a few snippets on the README, but it would be more attractive to show them in real time, in a little project.

**Why is this needed**:

It would be more attractive to new users who might be interested in using unform to have a quick overview of it in action.

**Is your enhancement request related to a problem? Please describe.**

Not a problem, just one enhancement.

**Comment by Fagneregomes** [comment]
I agree.

**Comment by 130591** [comment]
It is very common this type example, and also fast to implement, but would have to do with Diego as we should proceed.

**Comment by diego3g** [comment]
Great! I'll try adding some Code Sandboxes to README

**Comment by zaguiini** [comment]
Bump.

**Comment by jpedroschmitz** [comment]
Hey guys, we have been working on the new API and the documentation for the last weeks and now we have two playgrounds created, one for [ReactJS](https://codesandbox.io/embed/agitated-tdd-uf177?autoresize=1&expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark) e another for [React Native](https://snack.expo.io/@diego3g/1e9fb3)  🎉

Also, we are planning to have live previews in [docs](https://unform.dev/) (at least for React) 💜

Since it is resolved now, I am going to close this issue! 

Keep rocking 🚀
