### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by ghost** [Rocketseat/unform#12]
Fui aplicar em um projeto que utiliza reactstrap, mas toda vez que defino a linha:

`import { Form, Input } from "@rocketseat/unform";`

O console me lança esse erro:

> TypeError: Cannot read property 'indexOf' of undefined

Alguém sabe como resolvo isso?

**Comment by diego3g** [comment]
@tmalexandre We're using just english in this repo, please translate the other comments or issues :)

Can you send the whole error trace? Including the files that originated the error?

**Comment by tmalexandre** [comment]
Sorry, I'll write in English from now on. Here is the error image

![image](https://user-images.githubusercontent.com/50591193/57664592-39358680-75cf-11e9-889e-4c5691584ac2.png)

**Comment by diego3g** [comment]
@tmalexandre Does it happens as soon as you import the library? Do you have any Form or Input elements defined inside your component?

**Comment by tmalexandre** [comment]
**I'm posting a snippet of the code, I left it without render content because it is extensive**

import React from "react";

// reactstrap components
import {
  Button,
  Card,
  CardBody,
  FormGroup,
  Container,
  Row,
  Col,
  Collapse
} from "reactstrap";
// core components
import AuthHeader from "components/Headers/AuthHeader.jsx";

//Unform
import { Form, Input } from "@rocketseat/unform";

class PreRegister extends React.Component {
  constructor(props) {
    super(props);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.toggle = this.toggle.bind(this);
    this.state = { collapse: false };

  };

  handleSubmit(data) {
    console.log(data);
  };

  toggle(e) {
    if(e.target.getAttribute('id') === 'input-yes-cnpj')
      this.setState(state => ({ collapse: true }));
    else
      this.setState(state => ({ collapse: false }));  
  };

  render() {    
    return (
         // Extensive code
      );
}

**Comment by diego3g** [comment]
I need the render, please put the code inside http://gist.github.com

**Comment by pellizzetti** [comment]
Closing since user deleted his account.

**Comment by julianosirtori** [comment]
I had same error, I forgot to put name in element Input

**Comment by ev4ndropc** [comment]
> I had same error, I forgot to put name in element Input

solved my mistake, just put the name in the inputs
