### ISSUE TITLE
Attempted import error: 'Choice' is not exported from '@rocketseat/unform'.

### ISSUE THREAD

**Issue by PierreBosch** [Rocketseat/unform#131]
The option Choice does not appear on import, nor does autofill

**Comment by ROiPinheiro** [comment]
"Attempted import error: 'Choice' is not exported from '@rocketseat/unform'."

**Comment by fauker** [comment]
Same here 👍 

`Attempted import error: 'Choice' is not exported from '@rocketseat/unform'.`

**Comment by BohdanK911** [comment]
Same error!

**Comment by nomgains** [comment]
Any update on this?

**Comment by jpedroschmitz** [comment]
Hey guys, sorry for taking so long to answer. We were working on version 1.6.0, which would add the Choice and Check component, and the good news is that is was released now on #136 🎉 

If you need to use these components, do not forget to update unform to the latest version. You can achieve it by running `yarn upgrade unform@1.6.1` 🚀 

As the problem was solved, I am closing this issue now. If you need help with Unform, feel free to open an issue with a description of the problem you're facing or, if you prefer, you can chat with us on our [Discord Community](https://discordapp.com/invite/gCRAFhc) 💜
