### ISSUE TITLE
Render props?

### ISSUE THREAD

**Issue by akx** [Rocketseat/unform#158]
**What would you like to be added**:

Some sort of render props support for all basic field types to customize their rendering without having to deal with all of that `registerField()` boilerplate in custom components.

**Why is this needed**:

I'm using [`react-bootstrap` forms](https://react-bootstrap.netlify.com/components/forms/#forms) and as you may know, Bootstrap requires some wrapping for e.g. good-looking checkboxes.

Unform's [rendering of checkboxes](https://github.com/Rocketseat/unform/blob/cd0367c6cda74c3595f025374f4839b57570afef/lib/components/Check.tsx#L42-L50) doesn't quite cut it, but having a render prop would make it pretty simple to fix, and the refactoring isn't honestly very complicated either.

Just refactoring the final rendering bits out of each component into a function that returns react nodes (i.e. a render prop function), and allowing passing it as a prop to the component should be enough.

If this sounds sane, I could do the dev legwork.

**Comment by diego3g** [comment]
Hello @akx, you good? Unform released 2.0 🎉

And now we do not expose any form element inside the library, so all of the form elements must be created by the user.

Instead of exposing the components, we focused on upgrading the `useField` API and the examples, so you can integrate unform with all of your bootstrap inputs.

Check this guide to see an example of a simple input: https://unform.dev/recipes/simple-input

If you need any further help, feel free to open another issue with a Code Sandbox example so we can help you with the integration.
