### ISSUE TITLE
Handling errors after schema

### ISSUE THREAD

**Issue by leandrofinger** [Rocketseat/unform#159]
**Description of issue**

So many times I faced form not been submitted when using Schema because I made a mistake with field names or something like that. Is there any way to catch all the Yup errors in the Form component?

**Usage example**

```jsx
export default MyForm() {
  return (
    <Form onError={errors => console.log(errors)} schema={schema} /> 
  );
}
```

**UPDATE**
It also could be a debug flag, that prints in the console a message with all validation errors.
```jsx
<Form schema={schema} debug />
```

**Comment by diego3g** [comment]
Hello @leandrofinger, Unform released 2.0 🎉

Now the validation is fully out of the box, this means we do not include validation inside Unform package.

Instead of that, you can import your favorite validation library and use it inside the submit handler.

This also means you can customize the way the validation works, so you can disable what you asking by not providing the `stripUnknown: true` in [validate](https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-promiseany-validationerror) method options that was automatically added by unform.

Check this out: https://unform.dev/guides/validation
