### ISSUE TITLE
Update initialData does not update Choice Component to checked

### ISSUE THREAD

**Issue by diegojsanches** [Rocketseat/unform#167]
**Description of bug**
When update inicialData object with useEffect, all inputs are filled, but Checkbox input dont update state

**To Reproduce**

```
import React, { useState, useEffect } from "react";
import { Form, Input, Choice } from "@rocketseat/unform";

export default function App() {
  const [initial, setInitial] = useState();

  useEffect(() => {
    setInitial({ name: "Test Name", fieldName: ["1"] });
  }, []);

  return (
    <Form initialData={initial}>
      <Input name="name" />
      <Choice
        name="fieldName"
        options={[{ value: "1", label: "One" }, { value: "2", label: "Two" }]}
        multiple
      />
    </Form>
  );
}
```

The result: checkbox don't have checked

![Screenshot from 2020-01-22 14-49-11](https://user-images.githubusercontent.com/5012946/72919878-ff547c80-3d26-11ea-92f2-af6877f6b6f5.png)

**Expected behavior**
Checkbox checked  as the inicialData updated

![Screenshot from 2020-01-22 14-53-18](https://user-images.githubusercontent.com/5012946/72920578-5c046700-3d28-11ea-9f5f-78cfae9bf3c2.png)

**Exception or Error**
Does not have

**Environment**

- OS: Windows 10 and Ubuntu 18.04
- Browser: Firefox (72.0.1) and Chrome (73.0.3683.75)

**Comment by diego3g** [comment]
Hello @diegojsanches, you good?

Unform released version 2.0 🎉

Now unform does not include `Choice` component or any other form element inside the library. This means you'll need to create your custom fields using the `useField` API.

Instead of using the Choice component, maybe you can use the `react-select` integration so the user can choose between the options: https://unform.dev/third-party/react-select

I'm planning on including a guide to add checkbox/radio integration.

Also, `initialData` is meant to be used when you have the values synchronously. If you want to set the data of any input after an API request or any user action, use the form reference API instead: https://unform.dev/guides/initial-data#set-initial-data-asynchronously

Feel free to reopen the issue if you need any further help 💜
