### ISSUE TITLE
Cannot have 2 checks of the same name on a page

### ISSUE THREAD

**Issue by davecarlson** [Rocketseat/unform#170]
**Description of bug**

If you have 2 check boxes with the same name (but different scope) on the same page, ticking the top one affects the other

**To Reproduce**
```
<Scope path='reference1'>
<Check id='unexpiredWarnings-one' name='unexpiredWarnings' label='Unexpired Warnings?' />
</Scope>

<Scope path='reference2'>
<Check id='unexpiredWarnings-two' name='unexpiredWarnings' label='Unexpired Warnings?' />
</Scope>
```

**Steps to reproduce the behavior:**
Using the above code, when you press check in the second scope, it ticks the box on the first one.

**Expected behavior**
Checks should be independently managed.

**Exception or Error**

**Screenshots**

**Environment:**

**Additional context**

**Comment by diego3g** [comment]
Hello @diegojsanches, you good?

Unform released version 2.0 🎉

Now unform does not include Choice component or any other form element inside the library. This means you'll need to create your custom fields using the useField API.

Instead of using the Choice component, maybe you can use the react-select integration so the user can choose between the options: https://unform.dev/third-party/react-select

I'm planning on including a guide to add checkbox/radio integration.

Check the docs: https://unform.dev/

Feel free to reopen the issue if you need any further help 💜
