### ISSUE TITLE
validate on field blur, focus or change. + form state(isSubmitted)

### ISSUE THREAD

**Issue by diegoarcega** [Rocketseat/unform#229]
**What would you like to be added**:

- when to validate a certain field, onBlur, onFocus, onChange.
- form state if it has been submitted.

**Why is this needed**:
- Improvement of UX, user will know right away if the typed data is valid and correct as soon as possible.

**Is your enhancement request related to a problem? Please describe.**
- I now need to keep the isSubmitted state on my LoginPage component so I can check if the user has submitted the form so I can show the error when the user is typing but only if the user has submitted the form.
- clearError utility doesn't work because it removes the error completely and I need to revalidate onChange.

**Comment by giovanniantonaccio** [comment]
It would be really nice to have an option to validate onBlur, onFocus or onChange.

Maybe adding a `touched` attribute to the fields that the user has already interacted in some way and applying the validation just to them.

**Comment by Gabrielfcs** [comment]
It would be very good if we had an **`onChange`** of the form data to be able to validate using **Yup**!

**Comment by letalumil** [comment]
Agree, it would be really great if we could present a validation error right after the user's input, not after the submit.

**Comment by diego3g** [comment]
Hi guys, thanks for the discussion!

For now, Unform tries to not keep track of the state of the form, including submits or validations. 

That's why Unform cannot be compared to Formik, for example.

Everytime we keep track of some information inside Unform, we need to create a state so we can store that information and pass it along the children components of the form. Every state change cause a new rerender on the React componente, so everytime we'll have the whole tree of the form being updated just because the `submitted` state changed.

So, for now, i think the Unform should not keep track of the submitted state, the use should do that. You can also create your own form component that extends Unform's one and implement the submitted state.

About the validation on blur, focus, etc... Unform let's you create your custom inputs the way you want, so if you want to add any functionality to the input you can do it by adding listeners on it:

```js
<input onBlur={() => validateInput(fieldName)} />
```

Since Unform 2.0, the validation is something out of the box, so the form itself does not know if you're using schema validation or any other solution and i really think that we should not choose the validation library to the user, this should be a personal decision and each decision can change all of the way we deal with single inputs validations on blur, focus, etc...

**Comment by diegoarcega** [comment]
Hi Diego, thanks for replying. I respect the decisions taken but I'd like to make some additional comments.

1. I believe trade off of implementing a state within the form is worth it. Let's not be so strict with performance, the benefit of having a isSubmitted in state in my opinion brings more value than it  reduces the lib's performance. 

2. The validation could be passed down to the Form component and from there onwards the form will know how to validate the fields.  I did what you suggested as a 'workaround' let's say, but I was looking for something more out of the box.  If I have 4 pages with form, I will have to implement this validation function in all of the three pages or create a parallel util file to reuse in the other forms.

I do respect the goal of the lib to just support some features and let the user implement the necessary changes, but when looking for a Form library I want speed in development and not having to implement things on my own.

Thank you for this Lib by the way, it is pretty awesome!

**Comment by diego3g** [comment]
Hello @diegoarcega, i'm happy to have such a good discussion about this with you.

I can be wrong but i don't seed Unform as an library to have the same productivity in forms as Formik does. Unform is focused a lot in complex forms and performance, so i don't think that you should exclude all other form options when building smaller forms.

If you still think it would be great to unform to handle validation the way you proposed or submitted state, i would love to receive an API proposal with some code example to understand how we would achieve that without being just another form library in the React ecosystem.

Did you get what i'm trying to explain about the small percentage of complex forms that unform covers?

We still use Formik at some points and one library should never exclude others. There are points in Unform itself that explains why i didn't just make a pull request to formik.

**Comment by diegoarcega** [comment]
I wasn't aware Unform wasn't an alternative to Formik and all the others, ok now I understand it was meant to be different and to not  cover the cases I mentioned that should be covered. 

Maybe I need to dig a bit further then and really know the use case for Unform in contrast to the alternatives.

Thank you for this explanation.

**Comment by xinxilas** [comment]
What about give access from formref on usefield hook?

So we can use registerfield.(set, get, clear) to manipulate formref and be able to make an kind of formRef.isTouched by our own?
