### ISSUE TITLE
Remover chaves quando o valor for vazio

### ISSUE THREAD

**Issue by nicolasdezena** [Rocketseat/unform#261]
Galera, percebi que quando não digitamos nada no input e fazemos um getData(), o valor que vem por default é uma string vazia(''), isso me gerou problemas no Yup, pois o .date entende que foi passado algum valor, o que eu fiz foi a função abaixo, porém não sei se é a melhor forma(queria deixar isso de alguma forma global quando eu chamo o getData())

   ```
changeEmptyValueToNull(obj) {
    for(var key in obj) {
      if( null === obj[key] || "" === obj[key]) delete obj[key];
      if ( typeof obj[key] === 'object' ) this.changeEmptyValueToNull(obj[key]);
    }
    return obj
  }
```

**Comment by jpedroschmitz** [comment]
Hey @nicolasdezena, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
