### ISSUE TITLE
[ReactJS] Selecionar o valor padrão de um select ao resetar o form

### ISSUE THREAD

**Issue by Zigulich** [Rocketseat/unform#265]
**O que você gostaria que fosse adicionado?**:

Quando usada  a função reset() do form, os campos do tipo **select** seja resetados para seu valor **default** (definindo no option como **selected**) e não limpos.

**Por que isso é necessário?**:

Quando o usuário envia o formulário, não é necessário que ele selecione o select que já possui um valor padrão, somente quando há extrema necessidade. O que acaba gerando transtorno quando o select possui muitas opções.

**Sua solicitação de aprimoramento está relacionada a um problema? Por favor descreva.**

Sim, o usuário reportou que precisa sempre atualiza a página para que o select volte ao valor padrão, pois como há centenas de opções, é trabalhoso procurar e selecionar um valor que já está definindo como padrão naquela situação.

**Comment by jpedroschmitz** [comment]
Hey @Zigulich, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
