### ISSUE TITLE
Meu submit é limitado a 22 inputs usando o <Scope>, isso é normal?

### ISSUE THREAD

**Issue by arielff3** [Rocketseat/unform#282]
Aqui o retorno
![bb778e81-fc8d-4772-951a-e7eb39444cc2](https://user-images.githubusercontent.com/51038539/88487152-061fae80-cf59-11ea-9afa-735133eb7229.jpeg)

Aqui o código
![Captura de tela de 2020-07-26 16-00-41](https://user-images.githubusercontent.com/51038539/88487176-2ea7a880-cf59-11ea-9b7b-973c8f1b0989.png)

**Comment by carlosallexandre** [comment]
Hey @arielff3, 

Scope does not limit the number of Inputs. 

Give more details about your error.

**Comment by jpedroschmitz** [comment]
Hey @arielff3, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
