### ISSUE TITLE
onChangeText e onSubmitEditing não funcionam juntos

### ISSUE THREAD

**Issue by matheuscarvalho87** [Rocketseat/unform#285]
**Description of bug**

Dentro do meu input utilizando o unform estou usando o onSubmitEditing para validar o texto dentro do formulario e tentando utilizar o onChangeText para chamar uma função que preciso toda vez que o texto muda, mas usando os dois juntos o onSubmitEditing para de funcionar.

 Add information about your environment
 - [Windows10]
-  [React Native]

**Comment by jpedroschmitz** [comment]
Hey @matheuscarvalho87, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
