### ISSUE TITLE
Problemas ao usar setErrors com arrays

### ISSUE THREAD

**Issue by LucielVitorBS** [Rocketseat/unform#293]
Olá! Eu estou usando a função `setErrors` do `formRef`, quando adiciono um erro do tipo string, o erro vai correto, porém, quando tento setar algum erro do tipo Array, ele simplesmente não muda o error do `useField` para eu tratar no própio componente.
Encontrei uma solução alternativa, que é percorrer os erros retornados da api com o `Object.keys` e usando o `setFieldError` para adicionar os error do tipo Array.
Eu gostaria de saber se tem alguma maneira de setar esses erros em Array com o `setErrors`.

Exemplo que não seta os erros:
`formRef.current.setErrors({ prop: ['Mensagem de erro'] });`

Solução alternativa:
`Object.keys(errors).map(key =>
    formRef.current.setFieldError(key, errors[key]));`

**Comment by jpedroschmitz** [comment]
Hey @LucielVitorBS, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
