### ISSUE TITLE
Integração com react-imask

### ISSUE THREAD

**Issue by mayssalns** [Rocketseat/unform#320]
Alguém poderia me informar como fazer uma integração com o react-imask?

**Comment by jpedroschmitz** [comment]
Hey @mayssalns, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.

**Comment by mayssalns** [comment]
> Hey @mayssalns, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).
> 
> While contributing or interacting in any way in this project, refrain from using any language other than English.

Could you help me with the question?
