### ISSUE TITLE
Don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).

### ISSUE THREAD

**Issue by MonteiroIgor** [Rocketseat/unform#382]
Estou com esse erro ao implementar o handleSubmit para utilizar o unform/web.

![image](https://user-images.githubusercontent.com/31422943/112649180-f4b0de00-8e28-11eb-9ffe-0e7783653d45.png)

Mensagem de Erro:

![image](https://user-images.githubusercontent.com/31422943/112649352-1f029b80-8e29-11eb-903a-afa3cb6396ad.png)

Alguem poderia ajudar, tentei algumas configs do ban-types mas não deu certo.

**Comment by jpedroschmitz** [comment]
While contributing to this project, refrain from using any other language than English 💜 

Since it is in Portuguese, I need to close this issue. I highly recommend you translate it into English.

About the problem, have you checked the TypeScript guide? It's [in this link](https://unform.dev/recipes/typescript).

**Comment by MonteiroIgor** [comment]
> While contributing to this project, refrain from using any other language than English 💜
> 
> Since it is in Portuguese, I need to close this issue. I highly recommend you translate it into English.
> 
> About the problem, have you checked the TypeScript guide? It's [in this link](https://unform.dev/recipes/typescript).

Sorry, Guys.
