### ISSUE TITLE
Set errors from outside

### ISSUE THREAD

**Issue by PejmanNik** [Rocketseat/unform#88]
**What would you like to be added**:

Add setErrors function in the helper. it helps to set errors on submit.

**Why is this needed**:

Some time API returns validation errors after submitting data and we need to add each field related errors. (like unique validation)

**Comment by diego3g** [comment]
@PejmanNik So you need an easy way to set an input error manually from your component? If yes, then we'll discussing this here #76. I'll close this issue since we're probably talking about the same stuff here, can you complement the discussion with your necessity about `setError` function in the other issue?

Feel free to reopen it if you need to discuss anything more.
